sudo: false
dist: trusty

# A lightweight config
# I use my own config
language: c

branches:
  only:
    - master
#

script:
- agda --version
- tree
- git clone https://github.com/agda/agda-stdlib.git
- cp -r agda-stdlib/src .
- cd src
# - agda AllProofs.agda
- cd ..

# the agda compiler version in the Ubuntu source is too old to be used
# fuck Ubuntu

addons:
  apt:
    sources:
    - george-edison55-precise-backports
    - ubuntu-toolchain-r-test
    packages:
    - agda-mode
    - agda-stdlib
    - tree
#

cache:
  apt:
    true
#

