version: 2
jobs:
  build:
    docker:
      # terrorjack's awesome docker image
      # - image: terrorjack/rakuen:ghc-8.2.1.20171108
      - image: terrorjack/meikyu:ghc-8.2.1.20171108
    steps:
      - checkout
      - run:
          name: Install agda
          command: stack --resolver nightly install alex cpphs happy agda
      - run:
          name: Copy the stdlib to theorems
          command: |
            git clone https://github.com/agda/agda-stdlib.git
            cp -r agda-stdlib/src .
      - run:
          name: Build theorems
          command: agda src/Index.agda
