version: 2
jobs:
  build:
    docker:
      # terrorjack's awesome docker image
      # - image: terrorjack/rakuen:ghc-8.2.1.20171108
      - image: terrorjack/meikyu:ghc-8.2.1.20171108
    steps:
      - checkout
      - run:
          name: Install Agda
          command: stack --resolver nightly install alex cpphs happy Agda
          no_output_timeout: 12h
      - run:
          name: Copy the stdlib to theorems
          command: |
            git clone https://github.com/agda/agda-stdlib.git
            cp -r agda-stdlib/src .
      - run:
          name: Build theorems
          command: agda src/Index.agda
